### ISSUE TITLE
Call from bash

### ISSUE THREAD

**Issue by fcladera** [innogames/igcommit#4]
Hello!

I've been looking for a pre-receive hook for a long time, and this repo looks awesome!

Just a question regarding the use: I'm implementing a git pre-receive hook in bash, and I'd like to call `igcommit` from my bash script. Is this possible?

The use of bash is enforced by my git server.

Thanks!

**Comment by hasegeli** [comment]
Thank you.  You can wrap it in a bash script.  It just reads what Git provides to pre-receive hooks from the standard input.  I couldn't quite understand why wrapping it is necessary, though.  Which Git server are you using exactly?

**Comment by fcladera** [comment]
I'm using Gogs. They used to set a default pre-receive hook in bash (used for Gogs operation), hence the requirement of using bash.

Nonetheless, it seems that newer versions include a _user_ pre-receive hook via the web interface. I'll give a try to both solutions. Thanks for your help!
