### ISSUE TITLE
Commit#get_changed_files returns empty list for initial commit of a repos

### ISSUE THREAD

**Issue by lanisle** [innogames/igcommit#6]
I edited config.py to keep only phpcs check in it. Then I tested it with serval files of non-standard style in a initial commit. I found that the push is done without any remote output.

Here is the command executed, which output nothing:

git diff-tree -r --no-commit-id --break-rewrites --no-renames --diff-filter=AM 5620d9d89b45f2901adf13e0ab04e8dd07c39192

**Comment by hasegeli** [comment]
Apparently this command is not good enough to get the new files on the initial commit.  Thank you for reporting.  I will look into fixing this somehow.

**Comment by lanisle** [comment]
@hasegeli Thank you for fast reply. I added --root to the initial command and it works well. I've read man page of git diff-tree. It seems that the argument does not make side effect.

**Comment by hasegeli** [comment]
I added `--root` to the command.  Would you tell me your name to credit you on the change log of the next release?

**Comment by lanisle** [comment]
My full name is Zheng Wei. Thank you. :)
