### ISSUE TITLE
Issue on committing empty php file

### ISSUE THREAD

**Issue by lanisle** [innogames/igcommit#9]
> $ touch 2.php
$ git add 2.php
$ git commit -m 'test'
$ git push origin master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 321 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: === CheckCommand "phpcs" on 2.php at f5aafab3 ===
remote: ERROR: You must supply at least one file or directory to process.
remote: INFO:
remote: INFO: Usage: phpcs [-nwlsaepqvi] [-d key[=value]] [--colors] [--no-colors] [--stdin-path=<stdinPath>]
remote: INFO: [--report=<report>] [--report-file=<reportFile>] [--report-<report>=<reportFile>] ...
remote: INFO: [--report-width=<reportWidth>] [--generator=<generator>] [--tab-width=<tabWidth>]
remote: INFO: [--severity=<severity>] [--error-severity=<severity>] [--warning-severity=<severity>]
remote: INFO: [--runtime-set key value] [--config-set key value] [--config-delete key] [--config-show]
remote: INFO: [--standard=<standard>] [--sniffs=<sniffs>] [--exclude=<sniffs>] [--encoding=<encoding>]
remote: INFO: [--extensions=<extensions>] [--ignore=<patterns>] [--bootstrap=<bootstrap>]
remote: INFO: [--file-list=<fileList>] <file> ...
remote: INFO: Set runtime value (see --config-set)

Is this by design?

**Comment by hasegeli** [comment]
Not really.  I can easily check for files being empty and not bother checking them.  Thanks for the report.
